use regex::Regex;
use std::sync::LazyLock;

/// List of Claude Code internal XML tag names to strip.
const SYSTEM_TAGS: &[&str] = &[
    "local-command-caveat",
    "system-reminder",
    "command-name",
    "command-message",
    "command-args",
    "local-command-stdout",
    "local-command-stderr",
];

/// Build a single regex that matches all known system tags (paired).
/// Since the `regex` crate doesn't support backreferences, we generate
/// explicit alternations: `<tag>...</tag>` for each tag name.
static SYSTEM_TAG_RE: LazyLock<Regex> = LazyLock::new(|| {
    let paired: Vec<String> = SYSTEM_TAGS
        .iter()
        .map(|tag| format!(r"<{t}[^>]*>[\s\S]*?</{t}>", t = tag))
        .collect();
    let pattern = paired.join("|");
    Regex::new(&pattern).expect("invalid regex")
});

/// Regex for orphan opening tags (no matching close — happens when text was
/// truncated mid-tag), self-closing tags, and closing tags without openers.
static ORPHAN_TAG_RE: LazyLock<Regex> = LazyLock::new(|| {
    let tags = SYSTEM_TAGS
        .iter()
        .map(|t| regex::escape(t))
        .collect::<Vec<_>>()
        .join("|");
    // Match: <tag ...>, <tag .../>, </tag>, and truncated <tag>content-without-close
    let pattern = format!(r"</?(?:{tags})[^>]*(?:>|$)");
    Regex::new(&pattern).expect("invalid regex")
});

/// Strip Claude Code internal XML tags from a string, then trim whitespace.
pub fn strip_system_tags(input: &str) -> String {
    let pass1 = SYSTEM_TAG_RE.replace_all(input, "");
    let pass2 = ORPHAN_TAG_RE.replace_all(&pass1, "");
    // Collapse runs of whitespace left behind by removals
    let collapsed = pass2.split_whitespace().collect::<Vec<_>>().join(" ");
    collapsed
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_strips_local_command_caveat() {
        let input = r#"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>Hello world"#;
        assert_eq!(strip_system_tags(input), "Hello world");
    }

    #[test]
    fn test_strips_system_reminder() {
        let input = "Some text <system-reminder>reminder content here</system-reminder> more text";
        assert_eq!(strip_system_tags(input), "Some text more text");
    }

    #[test]
    fn test_strips_command_tags() {
        let input = "<command-name>/context</command-name>\n            <command-message>context</command-message>\n            <command-args></command-args>";
        assert_eq!(strip_system_tags(input), "");
    }

    #[test]
    fn test_preserves_normal_text() {
        let input = "Just a normal message with no tags";
        assert_eq!(
            strip_system_tags(input),
            "Just a normal message with no tags"
        );
    }

    #[test]
    fn test_strips_multiline_system_reminder() {
        let input = "before\n<system-reminder>\nExplanatory output style is active.\n</system-reminder>\nafter";
        assert_eq!(strip_system_tags(input), "before after");
    }

    #[test]
    fn test_empty_input() {
        assert_eq!(strip_system_tags(""), "");
    }
}
